name: Publish Node.js NPM

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Pre-requisites
        uses: actions/checkout@v2
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Run commands
        run: npm i
      - name: NPM publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
